server {
    listen 80 default_server;
    server_name localhost;

    absolute_redirect off;

    root /var/www/org.vici/public;
    index index.php index.html index.htm;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /vici {
        rewrite ^/vici/(.*)$ /item.php?id=$1 last;
    }

    location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root/$fastcgi_script_name;
        include        /etc/nginx/fastcgi_params;
        fastcgi_read_timeout 500;
    }

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
