server {
    listen       80;
    server_name  novo.vici.local;

    client_max_body_size 100M;

    location / {
        root   /var/www/local.vici.novo/public;
        try_files $uri @app;
    }

    location @app {
        fastcgi_pass   php:9000;
        fastcgi_param  SCRIPT_FILENAME  /var/www/local.vici.novo/app/controller.php;
        fastcgi_param SCRIPT_NAME     /controller.php;
        fastcgi_param QUERY_STRING    q=$uri&$args;
        include        fastcgi_params;
        fastcgi_read_timeout 500;
    }

}
