server {
    listen  80;
    listen  [::]:80; 

    server_name preview.vici.org;
    return 301 https://preview.vici.org$request_uri;
}

server {
    listen  443 ssl;
    listen  [::]:443 ssl;

    server_name preview.vici.org;

    add_header X-Frame-Options "SAMEORIGIN";
    client_max_body_size 100M;

    location / {
        root   /var/www/org.vici.preview/public;
        try_files $uri @app;
    }

    location @app {
        fastcgi_pass   unix:/run/php/php7.4-fpm.sock;
        fastcgi_param  SCRIPT_FILENAME  /var/www/org.vici.preview/app/controller.php;
        fastcgi_param SCRIPT_NAME     /controller.php;
        fastcgi_param QUERY_STRING    q=$uri&$args;
        include        fastcgi_params;
        fastcgi_read_timeout 500;
    }

    access_log /var/log/nginx/org.vici.preview.log;
}